- name: Set ST_HOME
  replace:
    path: "{{ miniconda_prefix }}/envs/{{ miniconda_env_name }}/etc/conda/activate.d/synda-transfer.sh"
    regexp: export ST_HOME=.*
    replace: export ST_HOME={{ st_home }}

- name: Create dataset directory
  file: state=directory dest={{ dataset }}

- name: Create synda dirs in {{ dataset }}
  file: state=directory dest={{ item }}
  with_items: ["{{ data }}", "{{ db }}", "{{ selection }}"]

- name: Template sdt.conf
  template: src=sdt.conf.j2 dest={{ st_home }}/conf/sdt.conf

- name: Template credentials.conf
  template: src=credentials.conf.j2 dest={{ st_home }}/conf/credentials.conf mode=0500

# Synda bugs
- name: Bypass unknown bug
  replace:
    path: "{{ miniconda_prefix }}/envs/{{ miniconda_env_name }}/lib/sd/sddao.py"
    regexp: 'def add_parameter_value.*\n.*conn.execute.*\n.*\n.*\n.*\n'
    replace: |
      def add_parameter_value(name,value,commit=True,conn=sddb.conn):
        if value != 'regular 1/2? lat-lon grid':
          conn.execute("insert into param (name,value) values (?,?)",(name,value))
          if commit:
            conn.commit()

- name: Avoid asserts
  copy: src=sdevent.py dest="{{ miniconda_prefix }}/envs/{{ miniconda_env_name }}/lib/sd/sdevent.py"
